"use client";

import Link from "next/link";
import { FormEventHandler, useState } from "react";

import { Loader2 } from "lucide-react";

import { Button } from "@/components/ui/button";

interface Props {
  qrCode: string;
  secretCode: string;
}

const TwoFactorForm = ({ qrCode, secretCode }: Props) => {
  const [showSecret, setShowSecret] = useState(false);
  const [loading, setLoading] = useState(false);
  const [msg, setMsg] = useState("");
  const [success, setSuccess] = useState(false);

  const handleSubmit: FormEventHandler<HTMLFormElement> = async (e) => {
    e.preventDefault();
    const formData = new FormData(e.currentTarget);

    const enteredCode = formData.get("enteredCode");

    try {
      setLoading(true);
      setMsg("");

      setSuccess(false);

      const res = await fetch("/api/auth/two-factor/set", {
        method: "POST",
        body: JSON.stringify({ enteredCode, secretCode }),
      });

      const resData = await res.json();

      if (res.status !== 200) {
        setMsg(resData.message);
      } else {
        setSuccess(true);
        setMsg(
          "MultiFactor (2-FA) Integration Success. Save the recovery codes"
        );
      }
    } catch (error) {
      setMsg("Server Error. Please try again later.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div>
      <h2 className="my-2 text-2xl font-bold">Step 1: Set up</h2>
      <div className="flex h-full flex-col flex-wrap justify-between border-2 md:flex-row">
        <div className="flex flex-1 flex-col items-center justify-center">
          <h3 className="my-2 text-xl font-semibold">Scan the qr code</h3>
          <img src={qrCode} alt="qr code" />
        </div>
        <div className="flex h-auto flex-1 flex-col items-center justify-center border-l-2">
          {showSecret ? (
            <p className="font-bold">{secretCode}</p>
          ) : (
            <p>Can&apos;t scan? Set up with code</p>
          )}
          <button
            onClick={() => setShowSecret((prev) => !prev)}
            className="my-2 rounded-md bg-blue-700 px-5 py-2 text-sm text-white"
          >
            {showSecret ? "Hide Code" : "Display Code"}
          </button>
        </div>
      </div>

      <h2 className="mb-2 mt-5 text-2xl font-bold">Step 2: Enter Code</h2>
      <form
        onSubmit={handleSubmit}
        className="mx-auto my-4 flex w-full flex-col gap-2 md:w-1/2 md:flex-row"
      >
        <input
          name="enteredCode"
          className="w-full rounded-md border-2 border-gray-700 bg-transparent px-2 py-2 md:w-3/4"
          type="text"
          required
          placeholder="Enter 6 digit code generated by your app"
        />

        <Button
          type="submit"
          variant="app"
          disabled={loading}
          className="flex items-center justify-center gap-2 rounded-md bg-blue-700 px-3 py-2 text-sm text-white"
        >
          {loading ? (
            <>
              <Loader2 className="mx-auto animate-spin" />
            </>
          ) : (
            <>Verify</>
          )}
        </Button>
      </form>

      <div className="flex w-full items-center justify-center">
        {msg && (
          <p
            className={` ${
              success ? "bg-green-600" : "bg-red-600"
            } my-5 w-fit rounded-md px-2 py-2 text-white`}
          >
            {msg}
          </p>
        )}
      </div>

      {success ? (
        <Button className="mx-auto mb-5 block w-fit" variant="app" asChild>
          <Link href="/recovery-codes">View Recovery Codes</Link>
        </Button>
      ) : null}
    </div>
  );
};

export default TwoFactorForm;
